git:
  log:
    showGraph: "never"
    showWholeGraph: true

customCommands:
  - key: "t"
    command: "git checkout --theirs {{ .SelectedFile.Name }}"
    context: "global"
    loadingText: "take theirs"
  - key: "o"
    command: "git checkout --ours {{ .SelectedFile.Name }}"
    context: "global"
    loadingText: "take ours"
