onboarding = false
[ui]
agent_panel_sort = "priority"

show_agent_labels_on_pane_borders = false
[experimental]
pane_history = false

[ui.toast]
delivery = "system"

[theme]
name = "gruvbox-light"
auto_switch = false
