return {
	-- "nvim-neotest/neotest",
	-- dependencies = {
	-- 	"nvim-neotest/nvim-nio",
	-- 	"nvim-lua/plenary.nvim",
	-- 	"antoinemadec/FixCursorHold.nvim",
	-- 	"nvim-treesitter/nvim-treesitter",
	-- 	"marilari88/neotest-vitest",
	-- },
	-- config = function()
	-- 	require("neotest").setup({
	-- 		adapters = {
	-- 			require("neotest-vitest"),
	-- 		},
	-- 		-- summary = {
	-- 		-- 	follow = false,
	-- 		-- },
	-- 	})
	--
	-- 	vim.keymap.set(
	-- 		"n",
	-- 		"<leader>tt",
	-- 		"<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<cr>",
	-- 		{ desc = "Run Watch" }
	-- 	)
	--
	-- 	vim.keymap.set(
	-- 		"n",
	-- 		"<leader>twr",
	-- 		"<cmd>lua require('neotest').run.run({ vitestCommand = 'vitest --watch' })<cr>",
	-- 		{ desc = "Run Watch" }
	-- 	)
	--
	-- 	vim.keymap.set(
	-- 		"n",
	-- 		"<leader>twf",
	-- 		"<cmd>lua require('neotest').run.run({ vim.fn.expand('%'), vitestCommand = 'vitest --watch' })<cr>",
	-- 		{ desc = "Run Watch File" }
	-- 	)
	-- end,
}
