[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/Codes"
desc = "Cd to ~/Codes"

[[mgr.prepend_keymap]]
on   = [ "g", "." ]
run  = "cd ~/.config"
desc = "Cd to ~/.config"

[[mgr.prepend_keymap]]
on   = [ "g", "F" ]
run  = 'search_do --via=fd --args="-d 3"'
desc = "Switch to flat view"

[[mgr.prepend_keymap]]
on   = "C"
run  = "plugin zip-hovered"
desc = "Zip hovered file"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd sftp://homeserver"
desc = "Go to home server"
